sites:

# domains without expiration date
  - client: ICC
      expiration: 2025-05-18T00:00:00
    url: icc.gg


  - client: ICC
      expiration: 2025-09-19T00:00:00
    url: ivancarlos.es


  - client: ICC
      expiration: 2025-09-19T00:00:00
    url: ivancarlos.eu

