sites:

# domains without expiration date
  - client: ICC
    url: icc.gg
    expiration: 2025-05-18T00:00:00

  - client: ICC
    url: ivancarlos.es
    expiration: 2025-09-19T00:00:00

  - client: ICC
    url: ivancarlos.eu
    expiration: 2025-09-19T00:00:00
