sites:

# domains without expiration date
  - propertyName: ICC
    domainName: icc.gg
    expiration: 2025-05-18T00:00:00

  - propertyName: ICC
    domainName: ivancarlos.es
    expiration: 2025-09-19T00:00:00

  - propertyName: ICC
    domainName: ivancarlos.eu
    expiration: 2025-09-19T00:00:00
