owner: ivancarlosti
repo: monitor2
user-agent: ivancarlosti

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

sites:
  - name: ICC.monitor
    client: ICC
    url: https://monitor.ivancarlos.com.br
    expectedStatusCodes:
      - 200
  - name: ICC.cloud
    client: ICC
    url: https://cloud.ivancarlos.com.br
    expectedStatusCodes:
      - 200
  - name: ICC.cloud2
    client: ICC
    url: https://cloud2.ivancarlos.com.br
    expectedStatusCodes:
      - 200
      
  - name: Punto.alerta
    client: Punto
    url: https://alerta.org.br
    expectedStatusCodes:
      - 200
  - name: SP4.sp4com
    client: SP4
    url: https://sp4com.com.br
    expectedStatusCodes:
      - 200
      - 301
  - name: SP4.sp4comunicacao
    client: SP4
    url: https://sp4comunicacao.com.br/en
    expectedStatusCodes:
      - 200
      
  - name: Bowler.bowlersv01.cp
    client: Bowler
    check: "tcp-ping"
    url: bowlersv01.bowler.com.br
    port: 22

  - name: Punto.puntosv01.cp
    client: Punto
    check: "tcp-ping"
    url: puntosv01.puntocomunicacao.com.br
    port: 22
  - name: Punto.puntosv07.cp
    client: Punto
    check: "tcp-ping"
    url: puntosv07.puntocomunicacao.com.br
    port: 22
  - name: Punto.puntosv09.cp
    client: Punto
    check: "tcp-ping"
    url: puntosv09.puntocomunicacao.com.br
    port: 22
  - name: Punto.puntosv11.cp
    client: Punto
    check: "tcp-ping"
    url: puntosv11.puntocomunicacao.com.br
    port: 22
  - name: Punto.puntosv12.cp
    client: Punto
    check: "tcp-ping"
    url: puntosv12.puntocomunicacao.com.br
    port: 22
  - name: Punto.oxfamsv01.cp
    client: Punto
    check: "tcp-ping"
    url: oxfamsv01.oxfam.org.br
    port: 22
  - name: Punto.oxfamsv02.cp
    client: Punto
    check: "tcp-ping"
    url: oxfamsv02.oxfam.org.br
    port: 22

  - name: FBSP.fbspsv01.cp
    client: FBSP
    check: "tcp-ping"
    url: fbspsv01.forumseguranca.org.br
    port: 22
  - name: FBSP.fbspsv02.cp
    client: FBSP
    check: "tcp-ping"
    url: fbspsv02.forumseguranca.org.br
    port: 22
  - name: FBSP.fbspsv03.cp
    client: FBSP
    check: "tcp-ping"
    url: fbspsv03.forumseguranca.org.br
    port: 22
  - name: FBSP.fbspsv04.cp
    client: FBSP
    check: "tcp-ping"
    url: fbspsv04.forumseguranca.org.br
    port: 22
  - name: FBSP.fbspsv05.cp
    client: FBSP
    check: "tcp-ping"
    url: fbspsv05.forumseguranca.org.br
    port: 22
    
  - name: ICC.iccsv01.cp
    client: ICC
    check: "tcp-ping"
    url: iccsv01.ivancarlos.com.br
    port: 22
  - name: ICC.iccsv02.cp
    client: ICC
    check: "tcp-ping"
    url: iccsv02.ivancarlos.com.br
    port: 22
  - name: ICC.iccsv03.cp
    client: ICC
    check: "tcp-ping"
    url: iccsv03.ivancarlos.com.br
    port: 22
  - name: ICC.iccsv04.cp
    client: ICC
    check: "tcp-ping"
    url: iccsv04.ivancarlos.com.br
    port: 22
  - name: ICC.iccsv05.cp
    client: ICC
    check: "tcp-ping"
    url: iccsv05.ivancarlos.com.br
    port: 22
  - name: ICC.iccsv06.cp
    client: ICC
    check: "tcp-ping"
    url: iccsv06.ivancarlos.com.br
    port: 22

domaintoget:
  - name: Z_Domain.almeida.com.br
    client: Z_Domain
    url: almeida.com.br
  - name: Z_Domain.aya.com
    client: Z_Domain
    url: aya.com
  - name: Z_Domain.aya.com.br
    client: Z_Domain
    url: aya.com.br
  - name: Z_Domain.icc.com
    client: Z_Domain
    url: icc.com
  - name: Z_Domain.ivancarlos.com
    client: Z_Domain
    url: ivancarlos.com

  - name: ICC.icc.gg
    client: ICC
     expiration: 2025-05-18T00:00:00
    url: icc.gg
  - name: ICC.ivancarlos.es
    client: ICC
    expiration: 2025-09-19T00:00:00
    url: ivancarlos.es
  - name: ICC.ivancarlos.eu
    client: ICC
    expiration: 2025-09-19T00:00:00
    url: ivancarlos.eu

    
status-website:
  theme: night
  css: "body { -webkit-user-select: none; -moz-user-select: none; -ms-user-select: none; -o-user-select: none; user-select: none; }"
  cname: monitor2.ivancarlos.com.br
  robotsText: "User-agent: * \n Allow: /"
  logoUrl: https://s3.sa-east-1.amazonaws.com/envio.ivancarlos.com.br/BNCnMqeS.png
  favicon: https://s3.sa-east-1.amazonaws.com/envio.ivancarlos.com.br/7vqI6o13.png
  faviconSvg: https://s3.sa-east-1.amazonaws.com/envio.ivancarlos.com.br/hGlsQKtB.svg
  name: "Monitor2 de Status"
  introTitle: "**Monitor2 de Status** is the secondary monitoring tool used by [**ICC**](https://ivancarlos.com.br) and hosted by [**GitHub**](https://github.com/)."
  introMessage: This monitor checks websites on hosting providers that blocks [**UptimeRobot**](https://icc.gg/uptimerobot), also checks control panels, dashboards~~, IPv6 reachability~~.
  customHeadHtml: "<!-- Google tag (gtag.js) --><script async src='https://www.googletagmanager.com/gtag/js?id=G-39VX59T3FR'></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','G-39VX59T3FR');</script>"
  customBodyHtml: "<!-- -->"
  js: "document.addEventListener('DOMContentLoaded',function(){var senha='ivancarlosconsultoria';var senhaDigitada=prompt('This status page is password protected.');if(senhaDigitada!==senha){alert('Access denied.');document.body.innerHTML='';window.location.href='https://monitor2.ivancarlos.com.br';}});document.addEventListener('contextmenu', event => event.preventDefault());"
  navbar:
    - title: ICC
      href: https://ivancarlos.com.br/
